### PR TITLE
customers#45 Downgrade compression-webpack-plugin to 6.1.1

### PR DESCRIPTION
**Pull request by oubchid**

### CODE REVIEW

**Review by tanandy — APPROVED** [review]

**Comment by tanandy** [comment]
why do we have error in tests @oubchid ?

**Comment by oubchid** [comment]
> why do we have error in tests @oubchid ?

I don't think that is related to the webpack module ! I didn't know why I will investigate that

**Comment by rezk2ll** [comment]
tests will work after we merge this https://github.com/linagora/esn-frontend-calendar/pull/591 and later you can rebase

**Comment by rezk2ll** [comment]
@oubchid you need to rebase this

**Review by rezk2ll — APPROVED** [review]

**Review by tanandy — APPROVED** [review]

**Pull request merged**
